### DISCUSSION TITLE
Using `bun-plugin-tailwind`

### DISCUSSION THREAD

**Discussion by saadeghi** [elysiajs/elysia#1167] [Q&A]
Is there a way to use `bun-plugin-tailwind` [like this](https://bun.sh/docs/bundler/fullstack#using-tailwindcss-in-html-routes) in Elysia?  

`bunfig.toml`
```toml
[serve.static]
plugins = ["bun-plugin-tailwind"]
```

I have CSS file with `@import "tailwindcss";` and I want Bun to make the CSS file (So I don't have to run Tailwind CLI, etc commands manually)
