### DISCUSSION TITLE
How to implement "--watch" / "--hot" of Bun with ElysiaJS while using Podman/Docker Compose?

### DISCUSSION THREAD

**Discussion by jdkcoder** [elysiajs/elysia#761] [Q&A]
I'm using Bun v1.1.21 with Elysia v1.1 but when I replace "--watch" with "--hot" but I still couldn't archive hot-reloading for development with Podman/Docker compose

The command of compose I used: `podman compose up -d --build`, afterI changed anything inside my project, nothing reloaded. Where did I go wrong?

Dockerfile
```dockerfile
FROM oven/bun

WORKDIR /app

COPY package*.json bun.lockb ./
RUN bun i
COPY . .

ENV NODE_ENV production

CMD [ "bun", "run", "--watch", "src/app.js" ]
```

docker-compose.yml
```yaml
services:
  app:
    image: "oven/bun"
    # override default entrypoint allows us to do `bun install` before serving
    entrypoint: []
    # execute bun install before we start the dev server in watch mode
    command: "/bin/sh -c 'bun i && bun run --watch src/app.js'"
    # expose the right ports
    ports: ["9000:5000"]
    # setup a host mounted volume to sync changes to the container
    volumes: ["./:/home/bun/app"]
```
