### ISSUE TITLE
--watch no function inside Dockerfile while running docker-compose

### ISSUE THREAD

**Issue by spanwair** [elysiajs/elysia#219]
Versions:
Elysia: 0.7.12 >
Bun: 1.0.3 >
Docker: 3

Issue:
I try to run my Elysia server in docker-compose while working on it. When I run it without --watch or --hot that there is no issue with quitting docker-compose but obviously server do not get refreshed.
Server is successfully installed and files get copied during docker-compose run. I tried many versions. Everything ends up with exited with code 0.
Issue is then in Bun Document is written that server get always restarted. So how to prevent it from being quitting?

Dockerfile:
FROM nwylynko/bun:0.2.0-alpine as development
WORKDIR /app
RUN apk add --no-cache bash
CMD ["/bin/bash", "-c", "(cd ./server && bun install && bun run --watch src/index.ts)"]

Err: (log from Dockerfile)
server            |  bun run dev
server            |    bun run --watch src/index.ts
server            | 
server            | 1 scripts
server exited with code 0

Update:
when I use dockerfile like this:
FROM oven/bun:1.0
WORKDIR /app 
COPY package.json .
COPY bun.lockb .
RUN bun install
COPY . .
EXPOSE 3033
CMD ["bun", "run", "--watch", "src/index.ts"]

than docker-compose do not exits but server is not reloading either

Expecting behavior:
bun with Elysia should detect changes in files and restart server just in the the same way as on local development does

**Comment by eelkevdbos** [comment]
For development, I'd recommend the following lean and mean docker compose setup:

```yaml
# docker-compose.yml
version: '3.9'

services:
  app:
    image: "oven/bun"
    # override default entrypoint allows us to do `bun install` before serving
    entrypoint: []
    # execute bun install before we start the dev server in watch mode
    command: "/bin/sh -c 'bun install && bun run --watch src/index.ts'"
    # expose the right ports
    ports: ["3000:3000"]
    # setup a host mounted volume to sync changes to the container
    volumes: [""./:/home/bun/app"]
```

And off you go:

```bash
docker compose up
```
